# Generated by Django 3.2.4 on 2021-06-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=300)),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
