# Generated by Django 3.2.4 on 2021-06-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('month', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ormapp.emp')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
