# Generated by Django 3.2.4 on 2021-07-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0003_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empqualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_per', models.IntegerField()),
                ('hsc_per', models.IntegerField()),
                ('gradu_per', models.IntegerField()),
                ('stream', models.CharField(max_length=50)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ormapp.emp')),
            ],
            options={
                'db_table': 'emp_qualif',
            },
        ),
    ]
